### PR TITLE
Add terraform code to test/demo atlantis

### PR DESCRIPTION
**Pull request by jbritt1**
Add atlantis.yaml file and environment folder

Add closing bracket

Change to our own state file for cleaner output:

Add module definition

Try to force actions to life

Add folder that should not trigger plan

Update atlantis.yml

Throw down some basic terraform Github Actions

Move this to another repo to demo cleaner

### CODE REVIEW

**Comment by jbritt1** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'apply_requirements' key: server-side config needs 'allowed_overrides: [apply_requirements]'
```

**Comment by jbritt1** [comment]
Ran Plan for project: `test` dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.bucket.aws_s3_bucket.bucket will be created
+ resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.57.221:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by jbritt1** [comment]
atlantis apply

**Comment by jbritt1** [comment]
Ran Apply for project: `test` dir: `environment/test` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Comment by dsva-atlantis** [comment]
**Plan Error**
```
parsing atlantis.yaml: workflows: (atlantis: (plan: (steps: (0: "fmt" is not a valid step type, maybe you omitted the 'run' key; 2: "validate" is not a valid step type, maybe you omitted the 'run' key.).).).).
```

**Comment by dsva-atlantis** [comment]
Ran Plan for dir: `environment/test` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/oddhoc/test/7/default/environment/test/test-default.tfplan\" -lock false" in "/home/atlantis/.atlantis/repos/oddhoc/test/7/default/environment/test": exit status 1
[32m[1mSuccess![0m The configuration is valid.
[0m

stat false: no such file or directory

```

**Comment by dsva-atlantis** [comment]
Ran Plan for dir: `environment/test` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/oddhoc/test/7/default/environment/test/test-default.tfplan\" -lock false" in "/home/atlantis/.atlantis/repos/oddhoc/test/7/default/environment/test": exit status 1
[32m[1mSuccess![0m The configuration is valid.
[0m

stat false: no such file or directory

```

**Comment by dsva-atlantis** [comment]
Ran Plan for project: `test` dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff
[32m[1mSuccess![0m The configuration is valid.
[0m


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.bucket.aws_s3_bucket.bucket will be created
+ resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.57.221:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Review by benniemosher — APPROVED** [review]

**Comment by dsva-atlantis** [comment]
Ran Plan for project: `test` dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.bucket.aws_s3_bucket.bucket will be created
+ resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.57.221:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by dsva-atlantis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `environment/test` workspace: `default`

**Pull request closed without merging**
