### PR TITLE
Add basic terraform code

### PR DESCRIPTION
**Pull request by benniemosher**

### CODE REVIEW

**Comment by benniemosher** [comment]
atlantis plan

**Comment by dsva-atlantis** [comment]
**Plan Error**
```
the default workspace is currently locked by another command that is running for this pull request–wait until the previous command is complete and try again
```

**Comment by dsva-atlantis** [comment]
Ran Plan for 0 projects:

**Comment by jbritt1** [comment]
atlantis plan

**Comment by dsva-atlantis** [comment]
**Plan Error**
```
the default workspace is currently locked by another command that is running for this pull request–wait until the previous command is complete and try again
```

**Comment by dsva-atlantis** [comment]
Ran Plan for 0 projects:

**Comment by dsva-atlantis** [comment]
**Plan Error**
```
the default workspace is currently locked by another command that is running for this pull request–wait until the previous command is complete and try again
```

**Comment by dsva-atlantis** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: line 5: did not find expected ',' or ']'
```

**Comment by dsva-atlantis** [comment]
**Plan Error**
```
the default workspace is currently locked by another command that is running for this pull request–wait until the previous command is complete and try again
```

**Comment by dsva-atlantis** [comment]
Ran Plan for dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_iam_account_password_policy.AccountPasswordPolicy will be destroyed
- resource "aws_iam_account_password_policy" "AccountPasswordPolicy" {
      - allow_users_to_change_password = true -> null
      - expire_passwords               = false -> null
      - hard_expiry                    = false -> null
      - id                             = "iam-account-password-policy" -> null
      - max_password_age               = 0 -> null
      - minimum_password_length        = 10 -> null
      - password_reuse_prevention      = 5 -> null
      - require_lowercase_characters   = true -> null
      - require_numbers                = true -> null
      - require_symbols                = true -> null
      - require_uppercase_characters   = true -> null
    }

  # aws_iam_group.Administrators will be destroyed
- resource "aws_iam_group" "Administrators" {
      - arn       = "arn:aws-us-gov:iam::268171240745:group/Administrators" -> null
      - id        = "Administrators" -> null
      - name      = "Administrators" -> null
      - path      = "/" -> null
      - unique_id = "AGPAL5KFUWXY6GKEIC5RU" -> null
    }

  # aws_iam_group.TestGroup will be destroyed
- resource "aws_iam_group" "TestGroup" {
      - arn       = "arn:aws-us-gov:iam::268171240745:group/TestGroup" -> null
      - id        = "TestGroup" -> null
      - name      = "TestGroup" -> null
      - path      = "/" -> null
      - unique_id = "AGPAKJOJQ4KGYO7MCT6NC" -> null
    }

  # aws_iam_group.adhoc-vetsgov-devops will be destroyed
- resource "aws_iam_group" "adhoc-vetsgov-devops" {
      - arn       = "arn:aws-us-gov:iam::268171240745:group/adhoc-vetsgov-devops" -> null
      - id        = "adhoc-vetsgov-devops" -> null
      - name      = "adhoc-vetsgov-devops" -> null
      - path      = "/" -> null
      - unique_id = "AGPAKTKCCHTKDWAXSKR7A" -> null
    }

  # aws_iam_group.dsva-appeals-devops will be destroyed
- resource "aws_iam_group" "dsva-appeals-devops" {
      - arn       = "arn:aws-us-gov:iam::268171240745:group/dsva-appeals-devops" -> null
      - id        = "dsva-appeals-devops" -> null
      - name      = "dsva-appeals-devops" -> null
      - path      = "/" -> null
      - unique_id = "AGPAK7PK2TYT6KF2MQSXW" -> null
    }

  # aws_iam_group.dsva-vetsgov-devops will be destroyed
- resource "aws_iam_group" "dsva-vetsgov-devops" {
      - arn       = "arn:aws-us-gov:iam::268171240745:group/dsva-vetsgov-devops" -> null
      - id        = "dsva-vetsgov-devops" -> null
      - name      = "dsva-vetsgov-devops" -> null
      - path      = "/" -> null
      - unique_id = "AGPAKDVZYEYI5N4S7AXVW" -> null
    }

  # aws_iam_group.force-MFA will be destroyed
- resource "aws_iam_group" "force-MFA" {
      - arn       = "arn:aws-us-gov:iam::268171240745:group/force-MFA" -> null
      - id        = "force-MFA" -> null
      - name      = "force-MFA" -> null
      - path      = "/" -> null
      - unique_id = "AGPALT3S2RD3HHKTJ3H4C" -> null
    }

  # aws_iam_group.temp-access-IAM will be destroyed
- resource "aws_iam_group" "temp-access-IAM" {
      - arn       = "arn:aws-us-gov:iam::268171240745:group/temp-access-IAM" -> null
      - id        = "temp-access-IAM" -> null
      - name      = "temp-access-IAM" -> null
      - path      = "/" -> null
      - unique_id = "AGPAL5W7Y5GJH6FAOWI34" -> null
    }

  # aws_iam_group_membership.Administrators will be destroyed
- resource "aws_iam_group_membership" "Administrators" {
      - group = "Administrators" -> null
      - id    = "Administrators" -> null
      - name  = "Administrators" -> null
      - users = [
          - "Aaron.Wieczorek",
          - "Bennie.Mosher",
          - "Bill.Ryan",
          - "Craig.Butler",
          - "Demian.Ginther",
          - "Glen.Stevenson",
          - "Jeremy.Britt",
          - "Lisa.Chung",
          - "Nathan.Hruby",
          - "Sunil.Sadasivan",
          - "Taylor.Skinner",
          - "Wyatt.Walter",
          - "enrique.valenzuela",
        ] -> null
    }

  # aws_iam_group_membership.TestGroup will be destroyed
- resource "aws_iam_group_membership" "TestGroup" {
      - group = "TestGroup" -> null
      - id    = "TestGroup" -> null
      - name  = "TestGroup" -> null
      - users = [
          - "Craig.Test",
        ] -> null
    }

  # aws_iam_group_membership.adhoc-vetsgov-devops will be destroyed
- resource "aws_iam_group_membership" "adhoc-vetsgov-devops" {
      - group = "adhoc-vetsgov-devops" -> null
      - id    = "adhoc-vetsgov-devops" -> null
      - name  = "adhoc-vetsgov-devops" -> null
      - users = [
          - "Bill.Ryan",
          - "Craig.Butler",
          - "Demian.Ginther",
          - "Nathan.Hruby",
          - "Patrick.Vinograd",
          - "Wyatt.Walter",
        ] -> null
    }

  # aws_iam_group_membership.dsva-appeals-devops will be destroyed
- resource "aws_iam_group_membership" "dsva-appeals-devops" {
      - group = "dsva-appeals-devops" -> null
      - id    = "dsva-appeals-devops" -> null
      - name  = "dsva-appeals-devops" -> null
      - users = [
          - "enrique.valenzuela",
        ] -> null
    }

  # aws_iam_group_membership.dsva-vetsgov-devops will be destroyed
- resource "aws_iam_group_membership" "dsva-vetsgov-devops" {
      - group = "dsva-vetsgov-devops" -> null
      - id    = "dsva-vetsgov-devops" -> null
      - name  = "dsva-vetsgov-devops" -> null
      - users = [
          - "Aaron.Wieczorek",
        ] -> null
    }

  # aws_iam_group_membership.force-MFA will be destroyed
- resource "aws_iam_group_membership" "force-MFA" {
      - group = "force-MFA" -> null
      - id    = "force-MFA" -> null
      - name  = "force-MFA" -> null
      - users = [
          - "Aaron.Wieczorek",
          - "Bennie.Mosher",
          - "Bill.Ryan",
          - "Craig.Butler",
          - "Craig.Test",
          - "Demian.Ginther",
          - "Glen.Stevenson",
          - "Jeremy.Britt",
          - "Lisa.Chung",
          - "Nathan.Hruby",
          - "Patrick.Vinograd",
          - "Sunil.Sadasivan",
          - "Taylor.Skinner",
          - "Wyatt.Walter",
          - "enrique.valenzuela",
        ] -> null
    }

  # aws_iam_group_membership.temp-access-IAM will be destroyed
- resource "aws_iam_group_membership" "temp-access-IAM" {
      - group = "temp-access-IAM" -> null
      - id    = "temp-access-IAM" -> null
      - name  = "temp-access-IAM" -> null
      - users = [
          - "Patrick.Vinograd",
        ] -> null
    }

  # aws_iam_group_policy.iam-role-and-cert will be destroyed
- resource "aws_iam_group_policy" "iam-role-and-cert" {
      - group  = "dsva-appeals-devops" -> null
      - id     = "dsva-appeals-devops:iam-role-and-cert" -> null
      - name   = "iam-role-and-cert" -> null
      - policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = [
                          - "iam:AddRoleToInstanceProfile",
                          - "iam:CreateRole",
                          - "iam:DeleteRole",
                          - "iam:DeleteServerCertificate",
                          - "iam:DeleteSigningCertificate",
                          - "iam:DetachRolePolicy",
                          - "iam:GetRole",
                          - "iam:ListAttachedGroupPolicies",
                          - "iam:ListAttachedRolePolicies",
                          - "iam:ListAttachedUserPolicies",
                          - "iam:ListGroups",
                          - "iam:ListGroupsForUser",
                          - "iam:ListInstanceProfiles",
                          - "iam:ListInstanceProfilesForRole",
                          - "iam:ListRolePolicies",
                          - "iam:ListRoles",
                          - "iam:ListServerCertificates",
                          - "iam:ListSigningCertificates",
                          - "iam:RemoveRoleFromInstanceProfile",
                          - "iam:UpdateServerCertificate",
                          - "iam:UpdateSigningCertificate",
                          - "iam:UploadServerCertificate",
                          - "iam:UploadSigningCertificate",
                          - "iam:ListPolicies",
                          - "iam:ListRolePolicies",
                          - "iam:CreateInstanceProfile",
                          - "iam:AttachRolePolicy",
                        ]
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = "Stmt1479137287421"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
    }

  # aws_iam_group_policy_attachment.AWSCloudTrailFullAccess-dsva-appeals-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AWSCloudTrailFullAccess-dsva-appeals-devops" {
      - group      = "dsva-appeals-devops" -> null
      - id         = "dsva-appeals-devops-002f8f6ec9c6dd81c3d36c2e09" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AWSCloudTrailFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AWSCloudTrailFullAccess-dsva-vetsgov-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AWSCloudTrailFullAccess-dsva-vetsgov-devops" {
      - group      = "dsva-vetsgov-devops" -> null
      - id         = "dsva-vetsgov-devops-002f8f6ec9c6dd81c3d36c2e02" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AWSCloudTrailFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AdministratorAccess-Administrators will be destroyed
- resource "aws_iam_group_policy_attachment" "AdministratorAccess-Administrators" {
      - group      = "Administrators" -> null
      - id         = "Administrators-20191028185431287200000001" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AdministratorAccess" -> null
    }

  # aws_iam_group_policy_attachment.AdministratorAccess-adhoc-vetsgov-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AdministratorAccess-adhoc-vetsgov-devops" {
      - group      = "adhoc-vetsgov-devops" -> null
      - id         = "adhoc-vetsgov-devops-20191028185431292000000002" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AdministratorAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonDynamoDBFullAccess-dsva-appeals-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonDynamoDBFullAccess-dsva-appeals-devops" {
      - group      = "dsva-appeals-devops" -> null
      - id         = "dsva-appeals-devops-002f8f6ec9c6dd81c3d36c2df8" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonDynamoDBFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonDynamoDBFullAccess-dsva-vetsgov-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonDynamoDBFullAccess-dsva-vetsgov-devops" {
      - group      = "dsva-vetsgov-devops" -> null
      - id         = "dsva-vetsgov-devops-002f8f6ec9c6dd81c3d36c2df4" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonDynamoDBFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonEC2FullAccess-dsva-appeals-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonEC2FullAccess-dsva-appeals-devops" {
      - group      = "dsva-appeals-devops" -> null
      - id         = "dsva-appeals-devops-002f8f6ec9c6dd81c3d36c2e01" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonEC2FullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonEC2FullAccess-dsva-vetsgov-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonEC2FullAccess-dsva-vetsgov-devops" {
      - group      = "dsva-vetsgov-devops" -> null
      - id         = "dsva-vetsgov-devops-002f8f6ec9c6dd81c3d36c2e0b" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonEC2FullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonElastiCacheFullAccess-dsva-appeals-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonElastiCacheFullAccess-dsva-appeals-devops" {
      - group      = "dsva-appeals-devops" -> null
      - id         = "dsva-appeals-devops-002f8f6ec9c6dd81c3d36c2e04" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonElastiCacheFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonElastiCacheFullAccess-dsva-vetsgov-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonElastiCacheFullAccess-dsva-vetsgov-devops" {
      - group      = "dsva-vetsgov-devops" -> null
      - id         = "dsva-vetsgov-devops-002f8f6ec9c6dd81c3d36c2e06" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonElastiCacheFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonRDSFullAccess-dsva-appeals-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonRDSFullAccess-dsva-appeals-devops" {
      - group      = "dsva-appeals-devops" -> null
      - id         = "dsva-appeals-devops-002f8f6ec9c6dd81c3d36c2df6" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonRDSFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonRDSFullAccess-dsva-vetsgov-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonRDSFullAccess-dsva-vetsgov-devops" {
      - group      = "dsva-vetsgov-devops" -> null
      - id         = "dsva-vetsgov-devops-002f8f6ec9c6dd81c3d36c2e0d" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonRDSFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonS3FullAccess-dsva-appeals-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonS3FullAccess-dsva-appeals-devops" {
      - group      = "dsva-appeals-devops" -> null
      - id         = "dsva-appeals-devops-002f8f6ec9c6dd81c3d36c2e0e" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonS3FullAccess" -> null
    }

  # aws_iam_group_policy_attachment.AmazonS3FullAccess-dsva-vetsgov-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "AmazonS3FullAccess-dsva-vetsgov-devops" {
      - group      = "dsva-vetsgov-devops" -> null
      - id         = "dsva-vetsgov-devops-002f8f6ec9c6dd81c3d36c2e05" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/AmazonS3FullAccess" -> null
    }

  # aws_iam_group_policy_attachment.CloudWatchFullAccess-dsva-appeals-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "CloudWatchFullAccess-dsva-appeals-devops" {
      - group      = "dsva-appeals-devops" -> null
      - id         = "dsva-appeals-devops-002f8f6ec9c6dd81c3d36c2dec" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/CloudWatchFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.CloudWatchFullAccess-dsva-vetsgov-devops will be destroyed
- resource "aws_iam_group_policy_attachment" "CloudWatchFullAccess-dsva-vetsgov-devops" {
      - group      = "dsva-vetsgov-devops" -> null
      - id         = "dsva-vetsgov-devops-002f8f6ec9c6dd81c3d36c2de4" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/CloudWatchFullAccess" -> null
    }

  # aws_iam_group_policy_attachment.Force_MFA-force-MFA will be destroyed
- resource "aws_iam_group_policy_attachment" "Force_MFA-force-MFA" {
      - group      = "force-MFA" -> null
      - id         = "force-MFA-00426e1e642b8d714505a76839" -> null
      - policy_arn = "arn:aws-us-gov:iam::268171240745:policy/Force_MFA" -> null
    }

  # aws_iam_group_policy_attachment.IAMFullAccess-temp-access-IAM will be destroyed
- resource "aws_iam_group_policy_attachment" "IAMFullAccess-temp-access-IAM" {
      - group      = "temp-access-IAM" -> null
      - id         = "temp-access-IAM-002f8f6ec9c6dd81c3d36c2e12" -> null
      - policy_arn = "arn:aws-us-gov:iam::aws:policy/IAMFullAccess" -> null
    }

  # aws_iam_policy.Force_MFA will be destroyed
- resource "aws_iam_policy" "Force_MFA" {
      - arn         = "arn:aws-us-gov:iam::268171240745:policy/Force_MFA" -> null
      - description = " " -> null
      - id          = "arn:aws-us-gov:iam::268171240745:policy/Force_MFA" -> null
      - name        = "Force_MFA" -> null
      - path        = "/" -> null
      - policy      = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = [
                          - "iam:ListAccountAliases",
                          - "iam:ListUsers",
                          - "iam:GetAccountSummary",
                        ]
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = "AllowAllUsersToListAccounts"
                    },
                  - {
                      - Action   = [
                          - "iam:ChangePassword",
                          - "iam:CreateAccessKey",
                          - "iam:CreateLoginProfile",
                          - "iam:DeleteAccessKey",
                          - "iam:DeleteLoginProfile",
                          - "iam:GetAccountPasswordPolicy",
                          - "iam:GetLoginProfile",
                          - "iam:ListAccessKeys",
                          - "iam:UpdateAccessKey",
                          - "iam:UpdateLoginProfile",
                        ]
                      - Effect   = "Allow"
                      - Resource = "arn:aws-us-gov:iam::268171240745:user/${aws:username}"
                      - Sid      = "AllowIndividualUserToSeeAndManageTheirOwnAccountInformation"
                    },
                  - {
                      - Action   = [
                          - "iam:ListVirtualMFADevices",
                          - "iam:ListMFADevices",
                        ]
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws-us-gov:iam::268171240745:mfa/*",
                          - "arn:aws-us-gov:iam::268171240745:user/${aws:username}",
                        ]
                      - Sid      = "AllowIndividualUserToListTheirOwnMFA"
                    },
                  - {
                      - Action   = [
                          - "iam:CreateVirtualMFADevice",
                          - "iam:DeactivateMFADevice",
                          - "iam:DeleteVirtualMFADevice",
                          - "iam:RequestSmsMfaRegistration",
                          - "iam:FinalizeSmsMfaRegistration",
                          - "iam:EnableMFADevice",
                          - "iam:ResyncMFADevice",
                        ]
                      - Effect   = "Allow"
                      - Resource = [
                          - "arn:aws-us-gov:iam::268171240745:mfa/${aws:username}",
                          - "arn:aws-us-gov:iam::268171240745:user/${aws:username}",
                        ]
                      - Sid      = "AllowIndividualUserToManageTheirOwnMFA"
                    },
                  - {
                      - Condition = {
                          - Bool = {
                              - aws:MultiFactorAuthPresent = "false"
                            }
                        }
                      - Effect    = "Deny"
                      - NotAction = "iam:*"
                      - Resource  = "*"
                      - Sid       = "BlockAnyAccessOtherThanAboveUnlessSignedInWithMFA"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
    }

  # aws_iam_user.AaronWieczorek will be destroyed
- resource "aws_iam_user" "AaronWieczorek" {
      - arn           = "arn:aws-us-gov:iam::268171240745:user/Aaron.Wieczorek" -> null
      - force_destroy = false -> null
      - id            = "Aaron.Wieczorek" -> null
      - name          = "Aaron.Wieczorek" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDALWTARE4DOIGJBO26S" -> null
    }

  # aws_iam_user.BennieMosher will be destroyed
- resource "aws_iam_user" "BennieMosher" {
      - arn       = "arn:aws-us-gov:iam::268171240745:user/Bennie.Mosher" -> null
      - id        = "Bennie.Mosher" -> null
      - name      = "Bennie.Mosher" -> null
      - path      = "/" -> null
      - tags      = {} -> null
      - unique_id = "AIDAT44CAMUUUWGQVEXNL" -> null
    }

  # aws_iam_user.BillRyan will be destroyed
- resource "aws_iam_user" "BillRyan" {
      - arn           = "arn:aws-us-gov:iam::268171240745:user/Bill.Ryan" -> null
      - force_destroy = false -> null
      - id            = "Bill.Ryan" -> null
      - name          = "Bill.Ryan" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDALBMYS7XHZYLHLRGR2" -> null
    }

  # aws_iam_user.CraigButler will be destroyed
- resource "aws_iam_user" "CraigButler" {
      - arn           = "arn:aws-us-gov:iam::268171240745:user/Craig.Butler" -> null
      - force_destroy = false -> null
      - id            = "Craig.Butler" -> null
      - name          = "Craig.Butler" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDALK2T2R5IP7CGIH5F4" -> null
    }

  # aws_iam_user.CraigTest will be destroyed
- resource "aws_iam_user" "CraigTest" {
      - arn           = "arn:aws-us-gov:iam::268171240745:user/Craig.Test" -> null
      - force_destroy = false -> null
      - id            = "Craig.Test" -> null
      - name          = "Craig.Test" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDALXQ7W2GRLACOZDLM6" -> null
    }

  # aws_iam_user.DemianGinther will be destroyed
- resource "aws_iam_user" "DemianGinther" {
      - arn       = "arn:aws-us-gov:iam::268171240745:user/Demian.Ginther" -> null
      - id        = "Demian.Ginther" -> null
      - name      = "Demian.Ginther" -> null
      - path      = "/" -> null
      - tags      = {} -> null
      - unique_id = "AIDAT44CAMUUVNTZJ2ZGL" -> null
    }

  # aws_iam_user.EnriqueValenzuela will be destroyed
- resource "aws_iam_user" "EnriqueValenzuela" {
      - arn           = "arn:aws-us-gov:iam::268171240745:user/enrique.valenzuela" -> null
      - force_destroy = false -> null
      - id            = "enrique.valenzuela" -> null
      - name          = "enrique.valenzuela" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDALJFJCQF4B76OKW7BU" -> null
    }

  # aws_iam_user.GlenStevenson will be destroyed
- resource "aws_iam_user" "GlenStevenson" {
      - arn       = "arn:aws-us-gov:iam::268171240745:user/Glen.Stevenson" -> null
      - id        = "Glen.Stevenson" -> null
      - name      = "Glen.Stevenson" -> null
      - path      = "/" -> null
      - tags      = {} -> null
      - unique_id = "AIDAT44CAMUUVRNG3WKY2" -> null
    }

  # aws_iam_user.JeremyBritt will be destroyed
- resource "aws_iam_user" "JeremyBritt" {
      - arn       = "arn:aws-us-gov:iam::268171240745:user/Jeremy.Britt" -> null
      - id        = "Jeremy.Britt" -> null
      - name      = "Jeremy.Britt" -> null
      - path      = "/" -> null
      - tags      = {} -> null
      - unique_id = "AIDAT44CAMUUQYB7NIN44" -> null
    }

  # aws_iam_user.LisaChung will be destroyed
- resource "aws_iam_user" "LisaChung" {
      - arn           = "arn:aws-us-gov:iam::268171240745:user/Lisa.Chung" -> null
      - force_destroy = false -> null
      - id            = "Lisa.Chung" -> null
      - name          = "Lisa.Chung" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDAKOUI44A6IZED73GE2" -> null
    }

  # aws_iam_user.NathanHruby will be destroyed
- resource "aws_iam_user" "NathanHruby" {
      - arn       = "arn:aws-us-gov:iam::268171240745:user/Nathan.Hruby" -> null
      - id        = "Nathan.Hruby" -> null
      - name      = "Nathan.Hruby" -> null
      - path      = "/" -> null
      - tags      = {} -> null
      - unique_id = "AIDAT44CAMUU5GYDM5LEM" -> null
    }

  # aws_iam_user.PatrickVinograd will be destroyed
- resource "aws_iam_user" "PatrickVinograd" {
      - arn           = "arn:aws-us-gov:iam::268171240745:user/Patrick.Vinograd" -> null
      - force_destroy = false -> null
      - id            = "Patrick.Vinograd" -> null
      - name          = "Patrick.Vinograd" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDALF2RHUP2APGTSVS7W" -> null
    }

  # aws_iam_user.SunilSadasivan will be destroyed
- resource "aws_iam_user" "SunilSadasivan" {
      - arn           = "arn:aws-us-gov:iam::268171240745:user/Sunil.Sadasivan" -> null
      - force_destroy = false -> null
      - id            = "Sunil.Sadasivan" -> null
      - name          = "Sunil.Sadasivan" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDAK5PG5PV55T34PXRMO" -> null
    }

  # aws_iam_user.TaylorSkinner will be destroyed
- resource "aws_iam_user" "TaylorSkinner" {
      - arn       = "arn:aws-us-gov:iam::268171240745:user/Taylor.Skinner" -> null
      - id        = "Taylor.Skinner" -> null
      - name      = "Taylor.Skinner" -> null
      - path      = "/" -> null
      - tags      = {} -> null
      - unique_id = "AIDAT44CAMUUUC3VKTFHM" -> null
    }

  # aws_iam_user.WyattWalter will be destroyed
- resource "aws_iam_user" "WyattWalter" {
      - arn           = "arn:aws-us-gov:iam::268171240745:user/Wyatt.Walter" -> null
      - force_destroy = false -> null
      - id            = "Wyatt.Walter" -> null
      - name          = "Wyatt.Walter" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "AIDALH3BYPHU2APH4BKAS" -> null
    }

  # aws_vpc.global-test-vpc will be destroyed
- resource "aws_vpc" "global-test-vpc" {
      - arn                              = "arn:aws-us-gov:ec2:us-gov-west-1:268171240745:vpc/vpc-10953175" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "172.30.0.0/20" -> null
      - default_network_acl_id           = "acl-2379f946" -> null
      - default_route_table_id           = "rtb-4047ca25" -> null
      - default_security_group_id        = "sg-a3ea70c6" -> null
      - dhcp_options_id                  = "dopt-19ae097c" -> null
      - enable_dns_hostnames             = true -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-10953175" -> null
      - instance_tenancy                 = "default" -> null
      - main_route_table_id              = "rtb-4047ca25" -> null
      - owner_id                         = "268171240745" -> null
      - tags                             = {
          - "Adminstration" = "TBD"
          - "Environment"   = "DEV"
          - "Name"          = "dsva-vetsgov-test-dev-vpc"
          - "Office"        = "tbd"
          - "ProjectName"   = "VA Vets.gov"
          - "ProjectShort"  = "Vets.gov"
          - "ResTag"        = "shared"
          - "Role"          = "tbd"
          - "VAECID"        = "AWG20180517003"
          - "dsva_version"  = "v2"
          - "environment"   = "test-dev"
          - "group"         = "dsva"
          - "managed"       = "terraform"
          - "office"        = "osva"
          - "project"       = "vagov"
          - "provider"      = "aws"
          - "region"        = "govcloud"
          - "suboffice"     = "cto"
        } -> null
    }

Plan: 0 to add, 0 to change, 51 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d environment/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.200.6:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d environment/test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by dsva-atlantis** [comment]
**Plan Error**
```
the default workspace is currently locked by another command that is running for this pull request–wait until the previous command is complete and try again
```

**Comment by dsva-atlantis** [comment]
Ran Plan for dir: `environment/test` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d environment/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.200.6:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d environment/test`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by dsva-atlantis** [comment]
**Plan Error**
```
the default workspace is currently locked by another command that is running for this pull request–wait until the previous command is complete and try again
```

**Comment by dsva-atlantis** [comment]
Ran Plan for dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.bucket.aws_s3_bucket.bucket will be created
+ resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d environment/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.200.6:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d environment/test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by dsva-atlantis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `environment/test` workspace: `default`

**Pull request closed without merging**
