### PR TITLE
Atlantis test

### PR DESCRIPTION
**Pull request by benniemosher**

### CODE REVIEW

**Comment by dsva-atlantis** [comment]
Ran Plan for dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.bucket.aws_s3_bucket.bucket will be created
+ resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d environment/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.200.6:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d environment/test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by dsva-atlantis** [comment]
Ran Plan for dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.bucket.aws_s3_bucket.bucket will be created
+ resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d environment/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.200.6:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d environment/test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by dsva-atlantis** [comment]
Ran Plan for dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.bucket.aws_s3_bucket.bucket will be created
+ resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d environment/test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.200.6:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d environment/test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by jbritt1** [comment]
atlantis plan

**Pull request closed without merging**
