### PR TITLE
Add terraform code to test/demo atlantis

### PR DESCRIPTION
**Pull request by jbritt1**

### CODE REVIEW

**Comment by dsva-atlantis** [comment]
Ran Plan for project: `test` dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.bucket.aws_s3_bucket.bucket will be created
+ resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.57.221:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by jbritt1** [comment]
atlantis apply

**Comment by dsva-atlantis** [comment]
Ran Apply for project: `test` dir: `environment/test` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Review by benniemosher — APPROVED** [review]

**Comment by jbritt1** [comment]
atlantis apply

**Comment by dsva-atlantis** [comment]
Ran Apply for project: `test` dir: `environment/test` workspace: `default`

**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/oddhoc/test/8/default/environment/test/test-default.tfplan\"" in "/home/atlantis/.atlantis/repos/oddhoc/test/8/default/environment/test": exit status 1
module.bucket.aws_s3_bucket.bucket: Creating...

Error: Error creating S3 bucket: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
	status code: 409, request id: F04C9CDA68FC1B57, host id: SaAn2Ja0A5HqZzyZ/pRvfidsMWHZdok47fHdZ6Yi+vSip7XyTlY8gTejxt2I6DMIdtwy8RSlNXw=

  on ../../modules/s3-bucket/main.tf line 1, in resource "aws_s3_bucket" "bucket":
   1: resource "aws_s3_bucket" "bucket" {



```

**Comment by dsva-atlantis** [comment]
Ran Plan for project: `test` dir: `environment/test` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.bucket.aws_s3_bucket.bucket will be created
+ resource "aws_s3_bucket" "bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "atlantis-demo-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.61.57.221:4141/lock?id=oddhoc%252Ftest%252Fenvironment%252Ftest%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by jbritt1** [comment]
atlantis apply

**Comment by dsva-atlantis** [comment]
Ran Apply for project: `test` dir: `environment/test` workspace: `default`

```diff
module.bucket.aws_s3_bucket.bucket: Creating...
module.bucket.aws_s3_bucket.bucket: Creation complete after 1s [id=atlantis-demo-bucket]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by jbritt1** [comment]
image

**Comment by benniemosher** [comment]
atlantis destroy

**Pull request closed without merging**
